# Export air temperature and relative hudmity for validation
- This script is used to export air temperature and relative humidity from simulations in comparison with sensor data;
- Simulations: CNTL, TRAF at UK-Manchester.

In [1]:
import os
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cftime
import string
import matplotlib.dates as mdates
home_path = '/gws/nopw/j04/duicv/yuansun/'

In [2]:
archive = f'{home_path}0_urban_traffic/archive'
start_date = '2012-01-01T00:00:00'
end_date = '2012-12-31T23:00:00'
case_list = ['cntl', 'traffic'] 
GRIDNAME_single = 'UK-MCR' 
var_list = ['TSA_U', 'RH2M']

In [3]:
df_all = pd.DataFrame()
for case in case_list:
    ds_case = xr.open_dataset(f'{archive}/{GRIDNAME_single}_{case}/lnd/hist/{GRIDNAME_single}_{case}.clm2.h0.2022-01-01-03600.nc')  
    for var in var_list:
        if var == 'RH2M':
            ds_case_var = ds_case[var] 
        else:    
            ds_case_var = ds_case[var] - 273.15
        df_case_var=ds_case_var.to_dataframe().reset_index()[['time', var]]
        df_case_var.rename(columns={var: f'{var}_{case}'}, inplace=True)
        df_case_var['time'] = df_case_var['time'].dt.round('min').dt.ceil('min')
        df_case_var['time'] = pd.to_datetime(df_case_var['time'])
        if df_all.empty:
            df_all = df_case_var
        else:
            df_all = pd.merge(df_all, df_case_var, how='outer', on='time')    
df_merged_clean = df_all[df_all['time'] < pd.to_datetime('2023-01-01')]  
df_merged_clean['time'] = df_merged_clean['time'] - pd.Timedelta(hours=1)   
df_merged_clean['hour'] = df_merged_clean['time'].dt.hour
df_merged_clean['minute'] = df_merged_clean['time'].dt.minute
df_merged_clean['diurnal'] = df_merged_clean['hour'].astype(str).str.zfill(2) + ':' + df_merged_clean['minute'].astype(str).str.zfill(2)
df_merged_clean.to_csv(f'./data_for_figure/UK-Manchester.csv', index=False)
df_merged_clean

/tmp/ipykernel_1827213/1043351946.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_clean['time'] = df_merged_clean['time'] - pd.Timedelta(hours=1)
/tmp/ipykernel_1827213/1043351946.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_clean['hour'] = df_merged_clean['time'].dt.hour
/tmp/ipykernel_1827213/1043351946.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_clean['minute'] = df_merged_clean['time'].dt.minute
/tmp/ipykernel_1827213/1043351946.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_clean['diurnal'] = df_merged_clean['hour'].astype(str).str.zfill(2) + ':' + df_merged_clean['minute'].astype(str).str.zfill(2)

,time,TSA_U_cntl,RH2M_cntl,TSA_U_traffic,RH2M_traffic,hour,minute,diurnal
0,2022-01-01 00:00:00,13.507690,87.172379,13.507690,87.172379,0,0,00:00
1,2022-01-01 01:00:00,13.702209,86.831398,13.743835,86.739693,1,0,01:00
2,2022-01-01 02:00:00,13.773071,86.172905,13.818451,86.056313,2,0,02:00
3,2022-01-01 03:00:00,13.429840,84.758057,13.458435,84.682343,3,0,03:00
4,2022-01-01 04:00:00,13.139038,83.672836,13.165070,83.607140,4,0,04:00
...,...,...,...,...,...,...,...,...
8754,2022-12-31 18:00:00,9.858551,98.132401,10.878296,95.779922,18,0,18:00
8755,2022-12-31 19:00:00,9.667816,97.870781,10.654022,95.734001,19,0,19:00
8756,2022-12-31 20:00:00,9.590485,97.950859,10.631500,95.576866,20,0,20:00
8757,2022-12-31 21:00:00,10.027008,95.632011,10.574005,93.893845,21,0,21:00
8758,2022-12-31 22:00:00,10.065521,93.313766,10.370514,92.338089,22,0,22:00

# Export HadUK-Grid data

In [20]:
haduk_path = '/badc/ukmo-hadobs/data/insitu/MOHC/HadOBS/HadUK-Grid/v1.3.1.ceda/1km/'
var_list = ['tas', 'tasmax', 'tasmin', 'pv']
ds = xr.open_dataset(f'{haduk_path}tas/mon/v20250415/tas_hadukgrid_uk_1km_mon_202201-202212.nc')
target_lat = 53.48017   
target_lon = -2.23233
abs_diff = np.abs(ds['latitude'] - target_lat) + np.abs(ds['longitude'] - target_lon)
iy, ix = np.unravel_index(abs_diff.argmin(), abs_diff.shape)

/tmp/ipykernel_1827213/1015332683.py:7: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  iy, ix = np.unravel_index(abs_diff.argmin(), abs_diff.shape)

In [23]:
var_monthly_list = []
for var in var_list:
    ds_var = xr.open_dataset(f'{haduk_path}{var}/mon/v20250415/{var}_hadukgrid_uk_1km_mon_202201-202212.nc')
    data_var = ds_var[var][:, iy, ix]
    df_data_var = data_var.to_dataframe().reset_index()[['time', var]]
    df_data_var.set_index('time', inplace=True)
    var_monthly_list.append(df_data_var)
df_haduk = pd.concat(var_monthly_list, axis=1).reset_index()
def pv_to_rh(pv, tas):
    es = 6.112 * np.exp((17.67 * tas) / (tas + 243.5))  # in hPa
    e = pv
    rh = (e / es) * 100.0  # in %
    return rh
df_haduk['rh'] = pv_to_rh(df_haduk['pv'], df_haduk['tas'])
df_haduk.drop(columns=['pv'], inplace=True)
df_haduk.to_csv(f'./data_for_figure/HadUK_1km_2022.csv', index=False)
df_haduk

         time        tas     tasmax     tasmin         rh
0  2022-01-16   6.009854   8.650368   3.314239  79.748261
1  2022-02-16   7.826240  10.593898   4.969867  77.376069
2  2022-03-16   8.773284  12.900686   4.649455  69.489798
3  2022-04-16  10.064879  14.217657   5.946359  67.773436
4  2022-05-16  14.097197  17.277759  10.780253  70.088428
5  2022-06-16  15.908314  20.086021  11.692735  66.133815
6  2022-07-16  18.578655  22.349227  14.762162  66.984597
7  2022-08-16  18.850972  23.548461  14.359891  67.121739
8  2022-09-16  15.201577  18.668172  11.785087  74.287986
9  2022-10-16  13.468494  16.305781  10.693884  81.769659
10 2022-11-16   9.803713  11.957003   7.598453  86.354547
11 2022-12-16   4.381732   7.146381   1.663022  85.878796